# Generated by Django 4.0.3 on 2022-11-04 14:40

from django.db import migrations, models
import django.db.models.deletion
import django_postgres_timestamp_without_tz


class Migration(migrations.Migration):

    dependencies = [
        ('trackerApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetype',
            name='workspace_id',
        ),
        migrations.RemoveField(
            model_name='workspaces',
            name='timetypd_id',
        ),
        migrations.AddField(
            model_name='gps',
            name='work_time_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trackerApi.work_time_period'),
        ),
        migrations.AddField(
            model_name='timetype',
            name='workspaces_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trackerApi.workspaces'),
        ),
        migrations.AlterField(
            model_name='gps',
            name='timestamp',
            field=django_postgres_timestamp_without_tz.DateTimeWithoutTZField(blank=True, default='2022-11-04 14:40:21'),
        ),
        migrations.AlterField(
            model_name='payroll_time_period',
            name='start_time',
            field=django_postgres_timestamp_without_tz.DateTimeWithoutTZField(default='2022-11-04 14:40:21', null=True),
        ),
        migrations.AlterField(
            model_name='work_time_period',
            name='start_time',
            field=django_postgres_timestamp_without_tz.DateTimeWithoutTZField(blank=True, default='2022-11-04 14:40:21'),
        ),
    ]
