# Generated by Django 4.0.3 on 2022-11-04 14:47

from django.db import migrations, models
import django.db.models.deletion
import django_postgres_timestamp_without_tz


class Migration(migrations.Migration):

    dependencies = [
        ('trackerApi', '0002_remove_timetype_workspace_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetype',
            name='workspaces_id',
        ),
        migrations.AddField(
            model_name='timetype',
            name='workspace_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetype', to='trackerApi.workspaces'),
        ),
        migrations.AlterField(
            model_name='gps',
            name='timestamp',
            field=django_postgres_timestamp_without_tz.DateTimeWithoutTZField(blank=True, default='2022-11-04 14:47:47'),
        ),
        migrations.AlterField(
            model_name='payroll_time_period',
            name='start_time',
            field=django_postgres_timestamp_without_tz.DateTimeWithoutTZField(default='2022-11-04 14:47:47', null=True),
        ),
        migrations.AlterField(
            model_name='work_time_period',
            name='start_time',
            field=django_postgres_timestamp_without_tz.DateTimeWithoutTZField(blank=True, default='2022-11-04 14:47:47'),
        ),
    ]
