# Generated by Django 4.0.3 on 2022-11-04 17:27

from django.db import migrations, models
import django.db.models.deletion
import django_postgres_timestamp_without_tz


class Migration(migrations.Migration):

    dependencies = [
        ('trackerApi', '0004_rename_workspace_id_timetype_workspace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gps',
            name='timestamp',
            field=django_postgres_timestamp_without_tz.DateTimeWithoutTZField(blank=True, default='2022-11-04 17:27:20'),
        ),
        migrations.AlterField(
            model_name='payroll_time_period',
            name='start_time',
            field=django_postgres_timestamp_without_tz.DateTimeWithoutTZField(default='2022-11-04 17:27:20', null=True),
        ),
        migrations.AlterField(
            model_name='timetype',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetype', to='trackerApi.workspaces'),
        ),
        migrations.AlterField(
            model_name='work_time_period',
            name='start_time',
            field=django_postgres_timestamp_without_tz.DateTimeWithoutTZField(blank=True, default='2022-11-04 17:27:20'),
        ),
    ]
