# Generated by Django 4.0.3 on 2022-11-04 19:35

from django.db import migrations, models
import django.db.models.deletion
import django_postgres_timestamp_without_tz


class Migration(migrations.Migration):

    dependencies = [
        ('trackerApi', '0005_alter_gps_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crew',
            name='workspace_id',
        ),
        migrations.RemoveField(
            model_name='gps',
            name='workspace_id',
        ),
        migrations.RemoveField(
            model_name='payroll_time_period',
            name='workspace_id',
        ),
        migrations.RemoveField(
            model_name='work',
            name='payroll_time_period_id',
        ),
        migrations.RemoveField(
            model_name='work',
            name='workspace_id',
        ),
        migrations.AddField(
            model_name='crew',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crew', to='trackerApi.workspaces'),
        ),
        migrations.AddField(
            model_name='gps',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gps', to='trackerApi.workspaces'),
        ),
        migrations.AddField(
            model_name='payroll_time_period',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_time_period', to='trackerApi.workspaces'),
        ),
        migrations.AddField(
            model_name='work',
            name='payroll_time_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work', to='trackerApi.payroll_time_period'),
        ),
        migrations.AddField(
            model_name='work',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work', to='trackerApi.workspaces'),
        ),
        migrations.AlterField(
            model_name='gps',
            name='timestamp',
            field=django_postgres_timestamp_without_tz.DateTimeWithoutTZField(blank=True, default='2022-11-04 19:35:25'),
        ),
        migrations.AlterField(
            model_name='gps',
            name='work_time_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gps', to='trackerApi.work_time_period'),
        ),
        migrations.AlterField(
            model_name='payroll_time_period',
            name='start_time',
            field=django_postgres_timestamp_without_tz.DateTimeWithoutTZField(default='2022-11-04 19:35:25', null=True),
        ),
        migrations.AlterField(
            model_name='work_time_period',
            name='start_time',
            field=django_postgres_timestamp_without_tz.DateTimeWithoutTZField(blank=True, default='2022-11-04 19:35:25'),
        ),
    ]
