# Generated by Django 4.0.3 on 2022-11-05 04:45

from django.db import migrations, models
import django.db.models.deletion
import django_postgres_timestamp_without_tz


class Migration(migrations.Migration):

    dependencies = [
        ('trackerApi', '0008_alter_gps_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crew',
            name='crew_user_ids',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='foreman_user_id',
        ),
        migrations.RemoveField(
            model_name='gps',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='payroll_time_period',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='work',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='work_time_period',
            name='timetype_id',
        ),
        migrations.RemoveField(
            model_name='work_time_period',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='work_time_period',
            name='work_id',
        ),
        migrations.RemoveField(
            model_name='work_time_period',
            name='workspace_id',
        ),
        migrations.AddField(
            model_name='crew',
            name='crew_users',
            field=models.ManyToManyField(blank=True, related_name='crew', to='trackerApi.user'),
        ),
        migrations.AddField(
            model_name='crew',
            name='foreman_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foreman_user', to='trackerApi.user'),
        ),
        migrations.AddField(
            model_name='gps',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gps', to='trackerApi.user'),
        ),
        migrations.AddField(
            model_name='payroll_time_period',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_time_period', to='trackerApi.user'),
        ),
        migrations.AddField(
            model_name='work',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work', to='trackerApi.user'),
        ),
        migrations.AddField(
            model_name='work_time_period',
            name='timetype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_time_period', to='trackerApi.timetype'),
        ),
        migrations.AddField(
            model_name='work_time_period',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_time_period', to='trackerApi.user'),
        ),
        migrations.AddField(
            model_name='work_time_period',
            name='work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_time_period', to='trackerApi.work'),
        ),
        migrations.AddField(
            model_name='work_time_period',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_time_period', to='trackerApi.workspaces'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspace', to='trackerApi.workspaces'),
        ),
        migrations.AlterField(
            model_name='gps',
            name='timestamp',
            field=django_postgres_timestamp_without_tz.DateTimeWithoutTZField(blank=True, default='2022-11-05 04:45:31'),
        ),
        migrations.AlterField(
            model_name='payroll_time_period',
            name='start_time',
            field=django_postgres_timestamp_without_tz.DateTimeWithoutTZField(default='2022-11-05 04:45:31', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='payroll_time_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work', to='trackerApi.payroll_time_period'),
        ),
        migrations.AlterField(
            model_name='work_time_period',
            name='start_time',
            field=django_postgres_timestamp_without_tz.DateTimeWithoutTZField(blank=True, default='2022-11-05 04:45:31'),
        ),
    ]
