# Generated by Django 4.0.3 on 2022-11-05 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_postgres_timestamp_without_tz


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trackerApi', '0010_alter_gps_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='crew_users',
            field=models.ManyToManyField(blank=True, related_name='crew_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='crew',
            name='foreman_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='crew',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trackerApi.workspaces'),
        ),
        migrations.AlterField(
            model_name='gps',
            name='timestamp',
            field=django_postgres_timestamp_without_tz.DateTimeWithoutTZField(blank=True, default='2022-11-05 15:23:58'),
        ),
        migrations.AlterField(
            model_name='gps',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payroll_time_period',
            name='start_time',
            field=django_postgres_timestamp_without_tz.DateTimeWithoutTZField(default='2022-11-05 15:23:58', null=True),
        ),
        migrations.AlterField(
            model_name='payroll_time_period',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_time_period', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='work',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='work_time_period',
            name='start_time',
            field=django_postgres_timestamp_without_tz.DateTimeWithoutTZField(blank=True, default='2022-11-05 15:23:58'),
        ),
        migrations.AlterField(
            model_name='work_time_period',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_time_period', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
