# Generated by Django 4.0.3 on 2022-11-07 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_postgres_timestamp_without_tz


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trackerApi', '0011_alter_crew_crew_users_alter_crew_foreman_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gps',
            name='timestamp',
            field=django_postgres_timestamp_without_tz.DateTimeWithoutTZField(blank=True, default='2022-11-07 01:08:44'),
        ),
        migrations.AlterField(
            model_name='gps',
            name='work_time_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trackerApi.work_time_period'),
        ),
        migrations.AlterField(
            model_name='gps',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trackerApi.workspaces'),
        ),
        migrations.AlterField(
            model_name='payroll_time_period',
            name='start_time',
            field=django_postgres_timestamp_without_tz.DateTimeWithoutTZField(default='2022-11-07 01:08:44', null=True),
        ),
        migrations.AlterField(
            model_name='work_time_period',
            name='start_time',
            field=django_postgres_timestamp_without_tz.DateTimeWithoutTZField(blank=True, default='2022-11-07 01:08:44'),
        ),
        migrations.AlterField(
            model_name='work_time_period',
            name='timetype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trackerApi.timetype'),
        ),
        migrations.AlterField(
            model_name='work_time_period',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='work_time_period',
            name='work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trackerApi.work'),
        ),
        migrations.AlterField(
            model_name='work_time_period',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trackerApi.workspaces'),
        ),
    ]
